[package]
edition = "2021"
name = "worker"
version = "1.6.1"

[dependencies]
bincode = "1"
comemo = "0.4"
protocol = { path = "../protocol" }
thiserror = "2"
worker-lib = { path = "../worker-lib" }

# Typst uses 0.24.
ttf-parser = "0.24"
typst = "0.13"

[build-dependencies]
cargo_metadata = "0.19"
