[workspace]
members = [
  "crates/bot", 
  "crates/protocol", 
  "crates/worker",
  "crates/worker-lib",
  "crates/http-server"
]
default-members = ["crates/bot"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
strip = true
