FROM rust:1.70 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --bin http-server

FROM debian:bullseye-slim
COPY --from=builder /usr/src/app/target/release/http-server /usr/local/bin/
EXPOSE 8080
CMD ["http-server"]
