version: "3.8"
services:
  typst-http:
    image: ghcr.io/premiertutors/typst-bot:http-server-main
    env_file:
      - .env
    environment:
      - CACHE_DIRECTORY=/app/cache
    volumes:
      - ./cache:/app/cache
    ports:
      - "8080:8080"